name: Setup-TF-Backend-$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: SetupBackend
    displayName: "🚀 Crear Backend Terraform en AWS"
    jobs:
      - job: DeployBackend
        displayName: "🛠️ Crear bucket y tabla para backend remoto"
        steps:
          - task: TerraformInstaller@1
            displayName: "📦 Instalar Terraform"
            inputs:
              terraformVersion: 'latest'

          - script: |
              echo "🔐 Configurando AWS CLI con variables de entorno"
              aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
              aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
              aws configure set region us-east-1
              aws sts get-caller-identity
            displayName: "🪪 Configurar credenciales AWS"
            env:
              AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
              AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)

          - script: |
              terraform init
              terraform apply -auto-approve
            workingDirectory: "$(System.DefaultWorkingDirectory)/backend-terraform"
            displayName: "🚀 Crear recursos de backend remoto"